# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Haiphen < Formula
  desc "Haiphen CLI — local gateway and command center for edge protocol intelligence"
  homepage "https://haiphen.io"
  version "0.2.10"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/haiphenAI/haiphen-cli/releases/download/v0.2.10/haiphen_0.2.10_darwin_amd64.tar.gz"
      sha256 "d9853c1efcd3a7037f13fb14cfbabed588b20ae0441637ce8f1a07f6585a128e"

      define_method(:install) do
        bin.install "haiphen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/haiphenAI/haiphen-cli/releases/download/v0.2.10/haiphen_0.2.10_darwin_arm64.tar.gz"
      sha256 "a5003266441cb2eae652a30c5f7f1ac665382f274b87c5dea11bd9f7ad168569"

      define_method(:install) do
        bin.install "haiphen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haiphenAI/haiphen-cli/releases/download/v0.2.10/haiphen_0.2.10_linux_amd64.tar.gz"
      sha256 "da98a38cdbb993d57d6fb201b4537129fcdcada6096d2cf4666a5ba875169234"
      define_method(:install) do
        bin.install "haiphen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haiphenAI/haiphen-cli/releases/download/v0.2.10/haiphen_0.2.10_linux_arm64.tar.gz"
      sha256 "adf22bbe044d875f32be41c238426ab6ca9b3b733a5354ec54525126ca3b7535"
      define_method(:install) do
        bin.install "haiphen"
      end
    end
  end

  test do
    system "#{bin}/haiphen", "--help"
  end
end
