# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Haiphen < Formula
  desc "Haiphen CLI — local gateway and command center for edge protocol intelligence"
  homepage "https://haiphen.io"
  version "0.2.10"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/haiphenAI/haiphen-cli/releases/download/v0.2.10/haiphen_0.2.10_darwin_amd64.tar.gz"
      sha256 "1283192b9042696d8b14105ce70bbcbe8ecc11172bf37c6745cd7bc30eb13c12"

      define_method(:install) do
        bin.install "haiphen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/haiphenAI/haiphen-cli/releases/download/v0.2.10/haiphen_0.2.10_darwin_arm64.tar.gz"
      sha256 "2b22a9d6d937948e4ede19c9fadbfa27aa3fed11c57db6958f81ea95f7712528"

      define_method(:install) do
        bin.install "haiphen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/haiphenAI/haiphen-cli/releases/download/v0.2.10/haiphen_0.2.10_linux_amd64.tar.gz"
      sha256 "f59330ba1b45244bd16ca94331952321391510b2d47a0c7fbb287ac71122fc5a"
      define_method(:install) do
        bin.install "haiphen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haiphenAI/haiphen-cli/releases/download/v0.2.10/haiphen_0.2.10_linux_arm64.tar.gz"
      sha256 "100efcc07d76ea1d3637014d6e091bf831205232cea99415fe4207859b16a3f7"
      define_method(:install) do
        bin.install "haiphen"
      end
    end
  end

  test do
    system "#{bin}/haiphen", "--help"
  end
end
